-- ============================================================================
-- Placely 프로젝트 Oracle DB 전체 테이블 생성 스크립트
-- ============================================================================

-- 실행 순서:
-- 1. Auth 서비스 테이블 (사용자 인증/인가)
-- 2. POS 서비스 테이블 (매장 운영 핵심)
-- 3. AI 서비스 테이블 (AI 추천/분석)

-- 기존 테이블 삭제 (개발 환경용 - 운영 환경에서는 주석 처리)
/*
-- AI 서비스 테이블 삭제
DROP TABLE AI_RECOMMENDATION_CACHE CASCADE CONSTRAINTS;
DROP TABLE AI_MODEL_PERFORMANCE CASCADE CONSTRAINTS;
DROP TABLE AI_PRODUCT_ASSOCIATIONS CASCADE CONSTRAINTS;
DROP TABLE AI_CUSTOMER_SEGMENT_MAPPING CASCADE CONSTRAINTS;
DROP TABLE AI_CUSTOMER_SEGMENTS CASCADE CONSTRAINTS;
DROP TABLE AI_SALES_PREDICTIONS CASCADE CONSTRAINTS;
DROP TABLE AI_RECOMMENDATIONS CASCADE CONSTRAINTS;
DROP TABLE AI_CUSTOMER_BEHAVIOR CASCADE CONSTRAINTS;

-- POS 서비스 테이블 삭제
DROP TABLE POS_INVENTORY_MOVEMENTS CASCADE CONSTRAINTS;
DROP TABLE POS_PAYMENTS CASCADE CONSTRAINTS;
DROP TABLE POS_SALE_ITEM_OPTIONS CASCADE CONSTRAINTS;
DROP TABLE POS_SALE_ITEMS CASCADE CONSTRAINTS;
DROP TABLE POS_SALES CASCADE CONSTRAINTS;
DROP TABLE POS_INVENTORY CASCADE CONSTRAINTS;
DROP TABLE POS_PRODUCT_OPTIONS CASCADE CONSTRAINTS;
DROP TABLE POS_PRODUCTS CASCADE CONSTRAINTS;
DROP TABLE POS_OPTION_ITEMS CASCADE CONSTRAINTS;
DROP TABLE POS_OPTION_GROUPS CASCADE CONSTRAINTS;
DROP TABLE POS_CATEGORIES CASCADE CONSTRAINTS;
DROP TABLE POS_STORES CASCADE CONSTRAINTS;
DROP TABLE POS_OWNERS CASCADE CONSTRAINTS;

-- Auth 서비스 테이블 삭제
DROP TABLE AUTH_TOKENS CASCADE CONSTRAINTS;
DROP TABLE AUTH_ROLE_PERMISSIONS CASCADE CONSTRAINTS;
DROP TABLE AUTH_PERMISSIONS CASCADE CONSTRAINTS;
DROP TABLE AUTH_USER_ROLES CASCADE CONSTRAINTS;
DROP TABLE AUTH_ROLES CASCADE CONSTRAINTS;
DROP TABLE AUTH_USERS CASCADE CONSTRAINTS;

-- 시퀀스 삭제
DROP SEQUENCE SEQ_AUTH_USERS;
DROP SEQUENCE SEQ_AUTH_ROLES;
DROP SEQUENCE SEQ_AUTH_PERMISSIONS;
DROP SEQUENCE SEQ_AUTH_TOKENS;
DROP SEQUENCE SEQ_POS_OWNERS;
DROP SEQUENCE SEQ_POS_STORES;
DROP SEQUENCE SEQ_POS_CATEGORIES;
DROP SEQUENCE SEQ_POS_OPTION_GROUPS;
DROP SEQUENCE SEQ_POS_OPTION_ITEMS;
DROP SEQUENCE SEQ_POS_PRODUCTS;
DROP SEQUENCE SEQ_POS_PRODUCT_OPTIONS;
DROP SEQUENCE SEQ_POS_INVENTORY;
DROP SEQUENCE SEQ_POS_SALES;
DROP SEQUENCE SEQ_POS_SALE_ITEMS;
DROP SEQUENCE SEQ_POS_SALE_ITEM_OPTIONS;
DROP SEQUENCE SEQ_POS_PAYMENTS;
DROP SEQUENCE SEQ_POS_INVENTORY_MOVEMENTS;
DROP SEQUENCE SEQ_AI_CUSTOMER_BEHAVIOR;
DROP SEQUENCE SEQ_AI_RECOMMENDATIONS;
DROP SEQUENCE SEQ_AI_SALES_PREDICTIONS;
DROP SEQUENCE SEQ_AI_CUSTOMER_SEGMENTS;
DROP SEQUENCE SEQ_AI_CUSTOMER_SEGMENT_MAPPING;
DROP SEQUENCE SEQ_AI_PRODUCT_ASSOCIATIONS;
DROP SEQUENCE SEQ_AI_MODEL_PERFORMANCE;
DROP SEQUENCE SEQ_AI_RECOMMENDATION_CACHE;
*/

-- 각 서비스별 DDL 실행
@@01_auth_tables.sql
@@02_pos_tables.sql
@@03_ai_tables.sql

-- 완료 메시지
SELECT 'Placely 데이터베이스 테이블 생성이 완료되었습니다.' AS MESSAGE FROM DUAL;

-- 생성된 테이블 확인
SELECT 'Auth 서비스 테이블' AS SERVICE, COUNT(*) AS TABLE_COUNT 
FROM USER_TABLES WHERE TABLE_NAME LIKE 'AUTH_%'
UNION ALL
SELECT 'POS 서비스 테이블' AS SERVICE, COUNT(*) AS TABLE_COUNT 
FROM USER_TABLES WHERE TABLE_NAME LIKE 'POS_%'
UNION ALL
SELECT 'AI 서비스 테이블' AS SERVICE, COUNT(*) AS TABLE_COUNT 
FROM USER_TABLES WHERE TABLE_NAME LIKE 'AI_%';

-- 시퀀스 확인
SELECT SEQUENCE_NAME, LAST_NUMBER 
FROM USER_SEQUENCES 
WHERE SEQUENCE_NAME LIKE 'SEQ_%'
ORDER BY SEQUENCE_NAME; 