-- ============================================================================
-- POS 서비스 테이블 (매장 운영 핵심 비즈니스)
-- ============================================================================

-- 점주 테이블
CREATE TABLE POS_OWNERS (
    OWNER_ID        NUMBER          PRIMARY KEY,
    EMAIL           VARCHAR2(100)   UNIQUE NOT NULL,
    PASSWORD_HASH   VARCHAR2(255)   NOT NULL,
    OWNER_NAME      VARCHAR2(100)   NOT NULL,
    PHONE           VARCHAR2(20),
    STATUS          VARCHAR2(20)    DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'INACTIVE')),
    CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
);

-- 매장 테이블
CREATE TABLE POS_STORES (
    STORE_ID        NUMBER          PRIMARY KEY,
    OWNER_ID        NUMBER          NOT NULL,
    STORE_NAME      VARCHAR2(100)   NOT NULL,
    STORE_CODE      VARCHAR2(20)    UNIQUE NOT NULL,
    ADDRESS         VARCHAR2(200),
    PHONE           VARCHAR2(20),
    BUSINESS_NUMBER VARCHAR2(20),
    OPEN_TIME       VARCHAR2(5),    -- HH:MM 형식
    CLOSE_TIME      VARCHAR2(5),    -- HH:MM 형식
    STATUS          VARCHAR2(20)    DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'MAINTENANCE')),
    CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (OWNER_ID) REFERENCES POS_OWNERS(OWNER_ID)
);

-- 카테고리 테이블
CREATE TABLE POS_CATEGORIES (
    CATEGORY_ID     NUMBER          PRIMARY KEY,
    CATEGORY_NAME   VARCHAR2(100)   NOT NULL,
    PARENT_ID       NUMBER,
    DISPLAY_ORDER   NUMBER          DEFAULT 0,
    STATUS          VARCHAR2(20)    DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'INACTIVE')),
    CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PARENT_ID) REFERENCES POS_CATEGORIES(CATEGORY_ID)
);

-- 옵션 그룹 테이블 (사이즈, 온도, 시럽 등)
CREATE TABLE POS_OPTION_GROUPS (
    OPTION_GROUP_ID NUMBER          PRIMARY KEY,
    GROUP_NAME      VARCHAR2(50)    NOT NULL,
    DESCRIPTION     VARCHAR2(200),
    CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
);

-- 옵션 항목 테이블 (S/M/L, 아이스/핫, 바닐라시럽 등)
CREATE TABLE POS_OPTION_ITEMS (
    OPTION_ITEM_ID  NUMBER          PRIMARY KEY,
    OPTION_GROUP_ID NUMBER          NOT NULL,
    ITEM_NAME       VARCHAR2(50)    NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (OPTION_GROUP_ID) REFERENCES POS_OPTION_GROUPS(OPTION_GROUP_ID)
);

-- 상품 테이블
CREATE TABLE POS_PRODUCTS (
    PRODUCT_ID      NUMBER          PRIMARY KEY,
    STORE_ID        NUMBER          NOT NULL,
    PRODUCT_NAME    VARCHAR2(200)   NOT NULL,
    PRODUCT_CODE    VARCHAR2(50)    NOT NULL,
    BARCODE         VARCHAR2(50),
    CATEGORY_ID     NUMBER,
    BASE_PRICE      NUMBER(10,2)    NOT NULL CHECK (BASE_PRICE >= 0),
    COST_PRICE      NUMBER(10,2)    CHECK (COST_PRICE >= 0),
    TAX_RATE        NUMBER(5,2)     DEFAULT 10.0,
    DESCRIPTION     VARCHAR2(500),
    IMAGE_URL       VARCHAR2(300),
    IS_ACTIVE       CHAR(1)         DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N')),
    CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (STORE_ID, PRODUCT_CODE),
    FOREIGN KEY (STORE_ID) REFERENCES POS_STORES(STORE_ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES POS_CATEGORIES(CATEGORY_ID)
);

-- 상품-옵션 연결 테이블 (상품별 사용 가능한 옵션과 추가 금액)
CREATE TABLE POS_PRODUCT_OPTIONS (
    PRODUCT_OPTION_ID NUMBER        PRIMARY KEY,
    PRODUCT_ID        NUMBER        NOT NULL,
    OPTION_ITEM_ID    NUMBER        NOT NULL,
    EXTRA_PRICE       NUMBER(10,2)  DEFAULT 0,
    CREATED_AT        TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (PRODUCT_ID, OPTION_ITEM_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES POS_PRODUCTS(PRODUCT_ID),
    FOREIGN KEY (OPTION_ITEM_ID) REFERENCES POS_OPTION_ITEMS(OPTION_ITEM_ID)
);

-- 재고 테이블
CREATE TABLE POS_INVENTORY (
    INVENTORY_ID    NUMBER          PRIMARY KEY,
    STORE_ID        NUMBER          NOT NULL,
    PRODUCT_ID      NUMBER          NOT NULL,
    CURRENT_STOCK   NUMBER          DEFAULT 0 CHECK (CURRENT_STOCK >= 0),
    MIN_STOCK       NUMBER          DEFAULT 0,
    MAX_STOCK       NUMBER,
    LAST_UPDATED    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (STORE_ID, PRODUCT_ID),
    FOREIGN KEY (STORE_ID) REFERENCES POS_STORES(STORE_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES POS_PRODUCTS(PRODUCT_ID)
);

-- 판매 테이블 (영수증 헤더)
CREATE TABLE POS_SALES (
    SALE_ID         NUMBER          PRIMARY KEY,
    STORE_ID        NUMBER          NOT NULL,
    CASHIER_ID      NUMBER          NOT NULL,
    RECEIPT_NUMBER  VARCHAR2(50)    UNIQUE NOT NULL,
    TOTAL_AMOUNT    NUMBER(12,2)    NOT NULL CHECK (TOTAL_AMOUNT >= 0),
    TAX_AMOUNT      NUMBER(12,2)    DEFAULT 0,
    DISCOUNT_AMOUNT NUMBER(10,2)    DEFAULT 0,
    PAYMENT_METHOD  VARCHAR2(20)    CHECK (PAYMENT_METHOD IN ('CASH', 'CARD', 'QR', 'MIXED')),
    SALE_DATE       TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    STATUS          VARCHAR2(20)    DEFAULT 'COMPLETED' CHECK (STATUS IN ('COMPLETED', 'CANCELLED', 'REFUNDED')),
    CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (STORE_ID) REFERENCES POS_STORES(STORE_ID)
);

-- 판매 상세 테이블 (영수증 라인)
CREATE TABLE POS_SALE_ITEMS (
    SALE_ITEM_ID    NUMBER          PRIMARY KEY,
    SALE_ID         NUMBER          NOT NULL,
    PRODUCT_ID      NUMBER          NOT NULL,
    QUANTITY        NUMBER          NOT NULL CHECK (QUANTITY > 0),
    BASE_PRICE      NUMBER(10,2)    NOT NULL CHECK (BASE_PRICE >= 0),
    TOTAL_AMOUNT    NUMBER(12,2)    NOT NULL CHECK (TOTAL_AMOUNT >= 0),
    DISCOUNT_AMOUNT NUMBER(10,2)    DEFAULT 0,
    TAX_AMOUNT      NUMBER(10,2)    DEFAULT 0,
    FOREIGN KEY (SALE_ID) REFERENCES POS_SALES(SALE_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES POS_PRODUCTS(PRODUCT_ID)
);

-- 판매 상세 옵션 테이블 (주문 시점의 옵션 기록)
CREATE TABLE POS_SALE_ITEM_OPTIONS (
    SALE_OPTION_ID    NUMBER        PRIMARY KEY,
    SALE_ITEM_ID      NUMBER        NOT NULL,
    PRODUCT_OPTION_ID NUMBER        NOT NULL,
    OPTION_NAME       VARCHAR2(50)  NOT NULL, -- 주문 시점 옵션명 보존
    OPTION_PRICE      NUMBER(10,2)  DEFAULT 0, -- 주문 시점 옵션 금액 보존
    FOREIGN KEY (SALE_ITEM_ID) REFERENCES POS_SALE_ITEMS(SALE_ITEM_ID),
    FOREIGN KEY (PRODUCT_OPTION_ID) REFERENCES POS_PRODUCT_OPTIONS(PRODUCT_OPTION_ID)
);

-- 결제 테이블
CREATE TABLE POS_PAYMENTS (
    PAYMENT_ID      NUMBER          PRIMARY KEY,
    SALE_ID         NUMBER          NOT NULL,
    PAYMENT_METHOD  VARCHAR2(20)    NOT NULL CHECK (PAYMENT_METHOD IN ('CASH', 'CARD', 'QR')),
    AMOUNT          NUMBER(12,2)    NOT NULL CHECK (AMOUNT > 0),
    CARD_NUMBER     VARCHAR2(20),   -- 마스킹된 카드번호
    APPROVAL_NUMBER VARCHAR2(50),
    PAYMENT_DATE    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    STATUS          VARCHAR2(20)    DEFAULT 'COMPLETED' CHECK (STATUS IN ('COMPLETED', 'CANCELLED')),
    FOREIGN KEY (SALE_ID) REFERENCES POS_SALES(SALE_ID)
);

-- 재고 이동 이력 테이블
CREATE TABLE POS_INVENTORY_MOVEMENTS (
    MOVEMENT_ID     NUMBER          PRIMARY KEY,
    STORE_ID        NUMBER          NOT NULL,
    PRODUCT_ID      NUMBER          NOT NULL,
    MOVEMENT_TYPE   VARCHAR2(20)    NOT NULL CHECK (MOVEMENT_TYPE IN ('IN', 'OUT', 'ADJUST')),
    QUANTITY        NUMBER          NOT NULL,
    REFERENCE_TYPE  VARCHAR2(20),   -- SALE, PURCHASE, ADJUSTMENT 등
    REFERENCE_ID    NUMBER,
    MOVEMENT_DATE   TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    NOTES           VARCHAR2(200),
    FOREIGN KEY (STORE_ID) REFERENCES POS_STORES(STORE_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES POS_PRODUCTS(PRODUCT_ID)
);

-- 시퀀스 생성
CREATE SEQUENCE SEQ_POS_OWNERS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_POS_STORES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_POS_CATEGORIES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_POS_OPTION_GROUPS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_POS_OPTION_ITEMS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_POS_PRODUCTS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_POS_PRODUCT_OPTIONS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_POS_INVENTORY START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_POS_SALES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_POS_SALE_ITEMS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_POS_SALE_ITEM_OPTIONS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_POS_PAYMENTS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_POS_INVENTORY_MOVEMENTS START WITH 1 INCREMENT BY 1;

-- 인덱스 생성
CREATE INDEX IDX_POS_PRODUCTS_CODE ON POS_PRODUCTS(PRODUCT_CODE);
CREATE INDEX IDX_POS_PRODUCTS_BARCODE ON POS_PRODUCTS(BARCODE);
CREATE INDEX IDX_POS_SALES_DATE ON POS_SALES(SALE_DATE);
CREATE INDEX IDX_POS_SALES_STORE ON POS_SALES(STORE_ID, SALE_DATE);
CREATE INDEX IDX_POS_INVENTORY_STORE_PRODUCT ON POS_INVENTORY(STORE_ID, PRODUCT_ID);

-- 기본 데이터 삽입
-- 점주 데이터
INSERT INTO POS_OWNERS (OWNER_ID, EMAIL, PASSWORD_HASH, OWNER_NAME, PHONE) VALUES 
(SEQ_POS_OWNERS.NEXTVAL, 'owner@placely.com', '$2a$10$example', '김사장', '010-1234-5678');

-- 매장 데이터  
INSERT INTO POS_STORES (STORE_ID, OWNER_ID, STORE_NAME, STORE_CODE, ADDRESS, PHONE, OPEN_TIME, CLOSE_TIME) VALUES 
(SEQ_POS_STORES.NEXTVAL, 1, '본점', 'MAIN001', '서울시 강남구 테헤란로 123', '02-1234-5678', '09:00', '22:00');

-- 카테고리 데이터
INSERT INTO POS_CATEGORIES (CATEGORY_ID, CATEGORY_NAME, DISPLAY_ORDER) VALUES 
(SEQ_POS_CATEGORIES.NEXTVAL, '음료', 1),
(SEQ_POS_CATEGORIES.NEXTVAL, '디저트', 2),
(SEQ_POS_CATEGORIES.NEXTVAL, '간식', 3);

-- 옵션 그룹 데이터
INSERT INTO POS_OPTION_GROUPS (OPTION_GROUP_ID, GROUP_NAME, DESCRIPTION) VALUES 
(SEQ_POS_OPTION_GROUPS.NEXTVAL, '사이즈', '음료 사이즈 선택'),
(SEQ_POS_OPTION_GROUPS.NEXTVAL, '온도', '음료 온도 선택'),
(SEQ_POS_OPTION_GROUPS.NEXTVAL, '시럽', '추가 시럽 선택');

-- 옵션 항목 데이터
INSERT INTO POS_OPTION_ITEMS (OPTION_ITEM_ID, OPTION_GROUP_ID, ITEM_NAME) VALUES 
(SEQ_POS_OPTION_ITEMS.NEXTVAL, 1, 'S'),
(SEQ_POS_OPTION_ITEMS.NEXTVAL, 1, 'M'),
(SEQ_POS_OPTION_ITEMS.NEXTVAL, 1, 'L'),
(SEQ_POS_OPTION_ITEMS.NEXTVAL, 2, '아이스'),
(SEQ_POS_OPTION_ITEMS.NEXTVAL, 2, '핫'),
(SEQ_POS_OPTION_ITEMS.NEXTVAL, 3, '바닐라시럽'),
(SEQ_POS_OPTION_ITEMS.NEXTVAL, 3, '카라멜시럽');

COMMIT; 