-- ============================================================================
-- AI 서비스 테이블 (AI 기반 추천 및 분석)
-- ============================================================================

-- 고객 행동 분석 테이블
CREATE TABLE AI_CUSTOMER_BEHAVIOR (
    BEHAVIOR_ID     NUMBER          PRIMARY KEY,
    STORE_ID        NUMBER          NOT NULL,
    SESSION_ID      VARCHAR2(100),
    CUSTOMER_TYPE   VARCHAR2(20)    CHECK (CUSTOMER_TYPE IN ('MEMBER', 'GUEST')),
    AGE_GROUP       VARCHAR2(20),   -- 10s, 20s, 30s, 40s, 50s, 60+
    GENDER          CHAR(1)         CHECK (GENDER IN ('M', 'F', 'U')),
    VISIT_TIME      TIMESTAMP       NOT NULL,
    VISIT_DURATION  NUMBER,         -- 분 단위
    TOTAL_AMOUNT    NUMBER(12,2),
    ITEMS_COUNT     NUMBER,
    BEHAVIOR_TYPE   VARCHAR2(50),   -- BROWSE, PURCHASE, RETURN 등
    CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
);

-- 상품 추천 이력 테이블
CREATE TABLE AI_RECOMMENDATIONS (
    RECOMMENDATION_ID   NUMBER      PRIMARY KEY,
    STORE_ID           NUMBER       NOT NULL,
    PRODUCT_ID         NUMBER       NOT NULL,
    CUSTOMER_ID        NUMBER,      -- NULL이면 익명 고객
    RECOMMENDATION_TYPE VARCHAR2(30) CHECK (RECOMMENDATION_TYPE IN ('POPULAR', 'SIMILAR', 'CROSS_SELL', 'SEASONAL')),
    SCORE_VALUE        NUMBER(5,2),  -- 추천 점수 (0-100)
    ALGORITHM_VERSION  VARCHAR2(20),
    RECOMMENDED_AT     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CLICKED           CHAR(1)       DEFAULT 'N' CHECK (CLICKED IN ('Y', 'N')),
    PURCHASED         CHAR(1)       DEFAULT 'N' CHECK (PURCHASED IN ('Y', 'N')),
    CLICKED_AT        TIMESTAMP,
    PURCHASED_AT      TIMESTAMP
);

-- 판매 예측 데이터 테이블
CREATE TABLE AI_SALES_PREDICTIONS (
    PREDICTION_ID   NUMBER          PRIMARY KEY,
    STORE_ID        NUMBER          NOT NULL,
    PRODUCT_ID      NUMBER          NOT NULL,
    PREDICTION_DATE DATE            NOT NULL,
    PREDICTED_QUANTITY NUMBER(10,2),
    PREDICTED_AMOUNT   NUMBER(12,2),
    CONFIDENCE_LEVEL   NUMBER(5,2), -- 신뢰도 (0-100)
    MODEL_VERSION      VARCHAR2(20),
    FACTORS            CLOB,        -- JSON 형태의 예측 요인들
    ACTUAL_QUANTITY    NUMBER(10,2), -- 실제 판매량 (예측 후 업데이트)
    ACTUAL_AMOUNT      NUMBER(12,2), -- 실제 판매금액
    CREATED_AT         TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT         TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (STORE_ID, PRODUCT_ID, PREDICTION_DATE)
);

-- 고객 세그먼트 테이블
CREATE TABLE AI_CUSTOMER_SEGMENTS (
    SEGMENT_ID      NUMBER          PRIMARY KEY,
    SEGMENT_NAME    VARCHAR2(100)   NOT NULL,
    DESCRIPTION     VARCHAR2(500),
    CRITERIA        CLOB,           -- JSON 형태의 세그먼트 기준
    CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    IS_ACTIVE       CHAR(1)         DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N'))
);

-- 고객-세그먼트 매핑 테이블
CREATE TABLE AI_CUSTOMER_SEGMENT_MAPPING (
    MAPPING_ID      NUMBER          PRIMARY KEY,
    CUSTOMER_ID     NUMBER          NOT NULL,
    SEGMENT_ID      NUMBER          NOT NULL,
    ASSIGNED_AT     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CONFIDENCE      NUMBER(5,2),    -- 소속 확신도 (0-100)
    FOREIGN KEY (SEGMENT_ID) REFERENCES AI_CUSTOMER_SEGMENTS(SEGMENT_ID)
);

-- 상품 연관 분석 테이블 (장바구니 분석)
CREATE TABLE AI_PRODUCT_ASSOCIATIONS (
    ASSOCIATION_ID  NUMBER          PRIMARY KEY,
    PRODUCT_A_ID    NUMBER          NOT NULL,
    PRODUCT_B_ID    NUMBER          NOT NULL,
    SUPPORT         NUMBER(8,6),    -- 지지도
    CONFIDENCE      NUMBER(8,6),    -- 신뢰도
    LIFT           NUMBER(8,6),     -- 향상도
    ANALYSIS_DATE   DATE            NOT NULL,
    MIN_SUPPORT     NUMBER(8,6),
    MIN_CONFIDENCE  NUMBER(8,6),
    TRANSACTION_COUNT NUMBER,
    CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (PRODUCT_A_ID, PRODUCT_B_ID, ANALYSIS_DATE)
);

-- AI 모델 성능 추적 테이블
CREATE TABLE AI_MODEL_PERFORMANCE (
    PERFORMANCE_ID  NUMBER          PRIMARY KEY,
    MODEL_NAME      VARCHAR2(100)   NOT NULL,
    MODEL_VERSION   VARCHAR2(20)    NOT NULL,
    METRIC_NAME     VARCHAR2(50)    NOT NULL, -- ACCURACY, PRECISION, RECALL, F1_SCORE 등
    METRIC_VALUE    NUMBER(10,6),
    TEST_DATA_SIZE  NUMBER,
    EVALUATION_DATE TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    NOTES           VARCHAR2(500)
);

-- 실시간 추천 캐시 테이블 (성능 최적화용)
CREATE TABLE AI_RECOMMENDATION_CACHE (
    CACHE_ID        NUMBER          PRIMARY KEY,
    CACHE_KEY       VARCHAR2(200)   UNIQUE NOT NULL, -- 고객ID_매장ID_타입 등의 조합
    RECOMMENDATIONS CLOB,           -- JSON 형태의 추천 목록
    CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    EXPIRES_AT      TIMESTAMP       NOT NULL,
    HIT_COUNT       NUMBER          DEFAULT 0
);

-- 시퀀스 생성
CREATE SEQUENCE SEQ_AI_CUSTOMER_BEHAVIOR START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_AI_RECOMMENDATIONS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_AI_SALES_PREDICTIONS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_AI_CUSTOMER_SEGMENTS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_AI_CUSTOMER_SEGMENT_MAPPING START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_AI_PRODUCT_ASSOCIATIONS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_AI_MODEL_PERFORMANCE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_AI_RECOMMENDATION_CACHE START WITH 1 INCREMENT BY 1;

-- 인덱스 생성
CREATE INDEX IDX_AI_BEHAVIOR_STORE_TIME ON AI_CUSTOMER_BEHAVIOR(STORE_ID, VISIT_TIME);
CREATE INDEX IDX_AI_RECOMMENDATIONS_STORE_PRODUCT ON AI_RECOMMENDATIONS(STORE_ID, PRODUCT_ID);
CREATE INDEX IDX_AI_PREDICTIONS_DATE ON AI_SALES_PREDICTIONS(PREDICTION_DATE);
CREATE INDEX IDX_AI_CACHE_EXPIRES ON AI_RECOMMENDATION_CACHE(EXPIRES_AT);

-- 기본 세그먼트 데이터 삽입
INSERT INTO AI_CUSTOMER_SEGMENTS (SEGMENT_ID, SEGMENT_NAME, DESCRIPTION, CRITERIA) VALUES (SEQ_AI_CUSTOMER_SEGMENTS.NEXTVAL, 'VIP 고객', '월 구매액 50만원 이상', '{"monthly_amount": {"min": 500000}}');
INSERT INTO AI_CUSTOMER_SEGMENTS (SEGMENT_ID, SEGMENT_NAME, DESCRIPTION, CRITERIA) VALUES (SEQ_AI_CUSTOMER_SEGMENTS.NEXTVAL, '단골 고객', '월 3회 이상 방문', '{"monthly_visits": {"min": 3}}');
INSERT INTO AI_CUSTOMER_SEGMENTS (SEGMENT_ID, SEGMENT_NAME, DESCRIPTION, CRITERIA) VALUES (SEQ_AI_CUSTOMER_SEGMENTS.NEXTVAL, '신규 고객', '첫 방문 후 1개월 이내', '{"days_since_first_visit": {"max": 30}}');
INSERT INTO AI_CUSTOMER_SEGMENTS (SEGMENT_ID, SEGMENT_NAME, DESCRIPTION, CRITERIA) VALUES (SEQ_AI_CUSTOMER_SEGMENTS.NEXTVAL, '이탈 위험 고객', '최근 30일간 방문 없음', '{"days_since_last_visit": {"min": 30}}');

COMMIT; 