-- ============================================================================
-- Placely 프로젝트 Oracle DB 전체 테이블 생성 스크립트 (코멘트 포함 버전)
-- ============================================================================

-- 한글 코멘트 포함, 기본키/외래키 정보 명시
-- Oracle SQL*Plus, SQL Developer, Toad 등에서 실행 가능합니다

-- ============================================================================
-- Auth 서비스 테이블 (인증/인가 관리)
-- ============================================================================

-- 사용자 테이블
CREATE TABLE AUTH_USERS (
    USER_ID         NUMBER          PRIMARY KEY,
    USERNAME        VARCHAR2(50)    UNIQUE NOT NULL,
    EMAIL           VARCHAR2(100)   UNIQUE NOT NULL,
    PASSWORD_HASH   VARCHAR2(255)   NOT NULL,
    PHONE           VARCHAR2(20),
    FULL_NAME       VARCHAR2(100)   NOT NULL,
    BIRTH_DATE      DATE,
    GENDER          CHAR(1)         CHECK (GENDER IN ('M', 'F')),
    STATUS          VARCHAR2(20)    DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'SUSPENDED')),
    LAST_LOGIN_AT   TIMESTAMP,
    CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY      NUMBER,
    UPDATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY      NUMBER,
    IS_DELETED      CHAR(1)         DEFAULT 'N' CHECK (IS_DELETED IN ('Y', 'N')),
    DELETED_AT      TIMESTAMP,
    DELETED_BY      NUMBER,
    FOREIGN KEY (CREATED_BY) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (UPDATED_BY) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (DELETED_BY) REFERENCES AUTH_USERS(USER_ID)
);

-- 컬럼 코멘트 추가
COMMENT ON COLUMN AUTH_USERS.USER_ID IS '사용자 ID (Primary Key)';
COMMENT ON COLUMN AUTH_USERS.USERNAME IS '사용자명 (로그인용)';
COMMENT ON COLUMN AUTH_USERS.EMAIL IS '이메일 주소';
COMMENT ON COLUMN AUTH_USERS.PASSWORD_HASH IS '암호화된 비밀번호';
COMMENT ON COLUMN AUTH_USERS.PHONE IS '연락처';
COMMENT ON COLUMN AUTH_USERS.FULL_NAME IS '실명';
COMMENT ON COLUMN AUTH_USERS.BIRTH_DATE IS '생년월일';
COMMENT ON COLUMN AUTH_USERS.GENDER IS '성별 (M:남성, F:여성)';
COMMENT ON COLUMN AUTH_USERS.STATUS IS '계정 상태 (ACTIVE:활성, INACTIVE:비활성, SUSPENDED:정지)';
COMMENT ON COLUMN AUTH_USERS.LAST_LOGIN_AT IS '최종 로그인 시간';
COMMENT ON COLUMN AUTH_USERS.CREATED_AT IS '생성 시간';
COMMENT ON COLUMN AUTH_USERS.CREATED_BY IS '생성자 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN AUTH_USERS.UPDATED_AT IS '수정 시간';
COMMENT ON COLUMN AUTH_USERS.UPDATED_BY IS '수정자 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN AUTH_USERS.IS_DELETED IS '삭제 여부 (Y:삭제, N:미삭제)';
COMMENT ON COLUMN AUTH_USERS.DELETED_AT IS '삭제 시간';
COMMENT ON COLUMN AUTH_USERS.DELETED_BY IS '삭제자 ID (Foreign Key: AUTH_USERS.USER_ID)';

-- 역할 테이블
CREATE TABLE AUTH_ROLES (
    ROLE_ID         NUMBER          PRIMARY KEY,
    ROLE_NAME       VARCHAR2(50)    UNIQUE NOT NULL,
    DESCRIPTION     VARCHAR2(200),
    CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY      NUMBER,
    UPDATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY      NUMBER,
    IS_DELETED      CHAR(1)         DEFAULT 'N' CHECK (IS_DELETED IN ('Y', 'N')),
    DELETED_AT      TIMESTAMP,
    DELETED_BY      NUMBER,
    FOREIGN KEY (CREATED_BY) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (UPDATED_BY) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (DELETED_BY) REFERENCES AUTH_USERS(USER_ID)
);

-- 컬럼 코멘트 추가
COMMENT ON COLUMN AUTH_ROLES.ROLE_ID IS '역할 ID (Primary Key)';
COMMENT ON COLUMN AUTH_ROLES.ROLE_NAME IS '역할명 (ADMIN, OWNER, MANAGER, CASHIER, USER)';
COMMENT ON COLUMN AUTH_ROLES.DESCRIPTION IS '역할 설명';
COMMENT ON COLUMN AUTH_ROLES.CREATED_AT IS '생성 시간';
COMMENT ON COLUMN AUTH_ROLES.CREATED_BY IS '생성자 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN AUTH_ROLES.UPDATED_AT IS '수정 시간';
COMMENT ON COLUMN AUTH_ROLES.UPDATED_BY IS '수정자 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN AUTH_ROLES.IS_DELETED IS '삭제 여부 (Y:삭제, N:미삭제)';
COMMENT ON COLUMN AUTH_ROLES.DELETED_AT IS '삭제 시간';
COMMENT ON COLUMN AUTH_ROLES.DELETED_BY IS '삭제자 ID (Foreign Key: AUTH_USERS.USER_ID)';

-- 사용자-역할 매핑 테이블
CREATE TABLE AUTH_USER_ROLES (
    USER_ID         NUMBER          NOT NULL,
    ROLE_ID         NUMBER          NOT NULL,
    GRANTED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    GRANTED_BY      NUMBER,
    PRIMARY KEY (USER_ID, ROLE_ID),
    FOREIGN KEY (USER_ID) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (ROLE_ID) REFERENCES AUTH_ROLES(ROLE_ID),
    FOREIGN KEY (GRANTED_BY) REFERENCES AUTH_USERS(USER_ID)
);

-- 컬럼 코멘트 추가
COMMENT ON COLUMN AUTH_USER_ROLES.USER_ID IS '사용자 ID (Primary Key, Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN AUTH_USER_ROLES.ROLE_ID IS '역할 ID (Primary Key, Foreign Key: AUTH_ROLES.ROLE_ID)';
COMMENT ON COLUMN AUTH_USER_ROLES.GRANTED_AT IS '권한 부여 시간';
COMMENT ON COLUMN AUTH_USER_ROLES.GRANTED_BY IS '권한 부여자 ID (Foreign Key: AUTH_USERS.USER_ID)';

-- 권한 테이블
CREATE TABLE AUTH_PERMISSIONS (
    PERMISSION_ID   NUMBER          PRIMARY KEY,
    PERMISSION_NAME VARCHAR2(100)   UNIQUE NOT NULL,
    RESOURCE_TYPE   VARCHAR2(100)   NOT NULL,
    ACTION_TYPE     VARCHAR2(50)    NOT NULL,
    DESCRIPTION     VARCHAR2(200),
    CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY      NUMBER,
    UPDATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY      NUMBER,
    IS_DELETED      CHAR(1)         DEFAULT 'N' CHECK (IS_DELETED IN ('Y', 'N')),
    DELETED_AT      TIMESTAMP,
    DELETED_BY      NUMBER,
    FOREIGN KEY (CREATED_BY) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (UPDATED_BY) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (DELETED_BY) REFERENCES AUTH_USERS(USER_ID)
);

-- 컬럼 코멘트 추가
COMMENT ON COLUMN AUTH_PERMISSIONS.PERMISSION_ID IS '권한 ID (Primary Key)';
COMMENT ON COLUMN AUTH_PERMISSIONS.PERMISSION_NAME IS '권한명';
COMMENT ON COLUMN AUTH_PERMISSIONS.RESOURCE_TYPE IS '리소스 타입';
COMMENT ON COLUMN AUTH_PERMISSIONS.ACTION_TYPE IS '액션 타입';
COMMENT ON COLUMN AUTH_PERMISSIONS.DESCRIPTION IS '권한 설명';
COMMENT ON COLUMN AUTH_PERMISSIONS.CREATED_AT IS '생성 시간';
COMMENT ON COLUMN AUTH_PERMISSIONS.CREATED_BY IS '생성자 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN AUTH_PERMISSIONS.UPDATED_AT IS '수정 시간';
COMMENT ON COLUMN AUTH_PERMISSIONS.UPDATED_BY IS '수정자 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN AUTH_PERMISSIONS.IS_DELETED IS '삭제 여부 (Y:삭제, N:미삭제)';
COMMENT ON COLUMN AUTH_PERMISSIONS.DELETED_AT IS '삭제 시간';
COMMENT ON COLUMN AUTH_PERMISSIONS.DELETED_BY IS '삭제자 ID (Foreign Key: AUTH_USERS.USER_ID)';

-- 역할-권한 매핑 테이블
CREATE TABLE AUTH_ROLE_PERMISSIONS (
    ROLE_ID         NUMBER          NOT NULL,
    PERMISSION_ID   NUMBER          NOT NULL,
    GRANTED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ROLE_ID, PERMISSION_ID),
    FOREIGN KEY (ROLE_ID) REFERENCES AUTH_ROLES(ROLE_ID),
    FOREIGN KEY (PERMISSION_ID) REFERENCES AUTH_PERMISSIONS(PERMISSION_ID)
);

-- 컬럼 코멘트 추가
COMMENT ON COLUMN AUTH_ROLE_PERMISSIONS.ROLE_ID IS '역할 ID (Primary Key, Foreign Key: AUTH_ROLES.ROLE_ID)';
COMMENT ON COLUMN AUTH_ROLE_PERMISSIONS.PERMISSION_ID IS '권한 ID (Primary Key, Foreign Key: AUTH_PERMISSIONS.PERMISSION_ID)';
COMMENT ON COLUMN AUTH_ROLE_PERMISSIONS.GRANTED_AT IS '권한 부여 시간';

-- 로그인 토큰 테이블
CREATE TABLE AUTH_TOKENS (
    TOKEN_ID        NUMBER          PRIMARY KEY,
    USER_ID         NUMBER          NOT NULL,
    TOKEN_TYPE      VARCHAR2(20)    DEFAULT 'ACCESS' CHECK (TOKEN_TYPE IN ('ACCESS', 'REFRESH')),
    TOKEN_VALUE      VARCHAR2(255)   NOT NULL,
    EXPIRES_AT      TIMESTAMP       NOT NULL,
    REVOKED_AT      TIMESTAMP,
    CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES AUTH_USERS(USER_ID)
);

-- 컬럼 코멘트 추가
COMMENT ON COLUMN AUTH_TOKENS.TOKEN_ID IS '토큰 ID (Primary Key)';
COMMENT ON COLUMN AUTH_TOKENS.USER_ID IS '사용자 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN AUTH_TOKENS.TOKEN_TYPE IS '토큰 타입 (ACCESS:액세스토큰, REFRESH:리프레시토큰)';
COMMENT ON COLUMN AUTH_TOKENS.TOKEN_VALUE IS '토큰 값';
COMMENT ON COLUMN AUTH_TOKENS.EXPIRES_AT IS '만료 시간';
COMMENT ON COLUMN AUTH_TOKENS.REVOKED_AT IS '폐기 시간';
COMMENT ON COLUMN AUTH_TOKENS.CREATED_AT IS '생성 시간';

-- ============================================================================
-- POS 서비스 테이블 (매장 운영 핵심 비즈니스)
-- ============================================================================

-- 점주 테이블
CREATE TABLE POS_OWNERS (
    USER_ID        NUMBER          PRIMARY KEY,
    OWNER_NAME     VARCHAR2(100)   NOT NULL,
    PHONE          VARCHAR2(20),
    STATUS         VARCHAR2(20)    DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'INACTIVE')),
    CREATED_AT     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY     NUMBER,
    UPDATED_AT     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY     NUMBER,
    IS_DELETED     CHAR(1)         DEFAULT 'N' CHECK (IS_DELETED IN ('Y', 'N')),
    DELETED_AT     TIMESTAMP,
    DELETED_BY     NUMBER,
    FOREIGN KEY (USER_ID) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (CREATED_BY) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (UPDATED_BY) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (DELETED_BY) REFERENCES AUTH_USERS(USER_ID)
);

-- 컬럼 코멘트 추가
COMMENT ON COLUMN POS_OWNERS.USER_ID IS '사용자 ID (Primary Key, Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN POS_OWNERS.OWNER_NAME IS '점주명';
COMMENT ON COLUMN POS_OWNERS.PHONE IS '연락처';
COMMENT ON COLUMN POS_OWNERS.STATUS IS '점주 상태 (ACTIVE:활성, INACTIVE:비활성)';
COMMENT ON COLUMN POS_OWNERS.CREATED_AT IS '생성 시간';
COMMENT ON COLUMN POS_OWNERS.CREATED_BY IS '생성자 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN POS_OWNERS.UPDATED_AT IS '수정 시간';
COMMENT ON COLUMN POS_OWNERS.UPDATED_BY IS '수정자 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN POS_OWNERS.IS_DELETED IS '삭제 여부 (Y:삭제, N:미삭제)';
COMMENT ON COLUMN POS_OWNERS.DELETED_AT IS '삭제 시간';
COMMENT ON COLUMN POS_OWNERS.DELETED_BY IS '삭제자 ID (Foreign Key: AUTH_USERS.USER_ID)';

-- 매장 테이블
CREATE TABLE POS_STORES (
    STORE_ID        NUMBER          PRIMARY KEY,
    USER_ID         NUMBER          NOT NULL,
    STORE_NAME      VARCHAR2(100)   NOT NULL,
    STORE_CODE      VARCHAR2(20)    UNIQUE NOT NULL,
    ADDRESS         VARCHAR2(200),
    PHONE           VARCHAR2(20),
    BUSINESS_NUMBER VARCHAR2(20),
    OPEN_TIME       VARCHAR2(5),
    CLOSE_TIME      VARCHAR2(5),
    STATUS          VARCHAR2(20)    DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'MAINTENANCE')),
    CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY      NUMBER,
    UPDATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY      NUMBER,
    IS_DELETED      CHAR(1)         DEFAULT 'N' CHECK (IS_DELETED IN ('Y', 'N')),
    DELETED_AT      TIMESTAMP,
    DELETED_BY      NUMBER,
    FOREIGN KEY (USER_ID) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (CREATED_BY) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (UPDATED_BY) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (DELETED_BY) REFERENCES AUTH_USERS(USER_ID)
);

-- 컬럼 코멘트 추가
COMMENT ON COLUMN POS_STORES.STORE_ID IS '매장 ID (Primary Key)';
COMMENT ON COLUMN POS_STORES.USER_ID IS '점주 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN POS_STORES.STORE_NAME IS '매장명';
COMMENT ON COLUMN POS_STORES.STORE_CODE IS '매장 코드';
COMMENT ON COLUMN POS_STORES.ADDRESS IS '매장 주소';
COMMENT ON COLUMN POS_STORES.PHONE IS '매장 연락처';
COMMENT ON COLUMN POS_STORES.BUSINESS_NUMBER IS '사업자 번호';
COMMENT ON COLUMN POS_STORES.OPEN_TIME IS '개점 시간 (HH:MM 형식)';
COMMENT ON COLUMN POS_STORES.CLOSE_TIME IS '폐점 시간 (HH:MM 형식)';
COMMENT ON COLUMN POS_STORES.STATUS IS '매장 상태 (ACTIVE:운영, INACTIVE:비활성, MAINTENANCE:점검중)';
COMMENT ON COLUMN POS_STORES.CREATED_AT IS '생성 시간';
COMMENT ON COLUMN POS_STORES.CREATED_BY IS '생성자 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN POS_STORES.UPDATED_AT IS '수정 시간';
COMMENT ON COLUMN POS_STORES.UPDATED_BY IS '수정자 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN POS_STORES.IS_DELETED IS '삭제 여부 (Y:삭제, N:미삭제)';
COMMENT ON COLUMN POS_STORES.DELETED_AT IS '삭제 시간';
COMMENT ON COLUMN POS_STORES.DELETED_BY IS '삭제자 ID (Foreign Key: AUTH_USERS.USER_ID)';

-- 매장별 사용자 역할 매핑 테이블
CREATE TABLE POS_STORE_USER_ROLES (
    STORE_USER_ROLE_ID  NUMBER          PRIMARY KEY,
    STORE_ID            NUMBER          NOT NULL,
    USER_ID             NUMBER          NOT NULL,
    ROLE_ID             NUMBER          NOT NULL,
    GRANTED_AT          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    GRANTED_BY          NUMBER,
    EXPIRES_AT          TIMESTAMP,
    STATUS              VARCHAR2(20)    DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'SUSPENDED')),
    NOTES               VARCHAR2(500),
    CREATED_AT          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY          NUMBER,
    UPDATED_AT          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY          NUMBER,
    IS_DELETED          CHAR(1)         DEFAULT 'N' CHECK (IS_DELETED IN ('Y', 'N')),
    DELETED_AT          TIMESTAMP,
    DELETED_BY          NUMBER,
    UNIQUE (STORE_ID, USER_ID, ROLE_ID),
    FOREIGN KEY (STORE_ID) REFERENCES POS_STORES(STORE_ID),
    FOREIGN KEY (USER_ID) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (ROLE_ID) REFERENCES AUTH_ROLES(ROLE_ID),
    FOREIGN KEY (GRANTED_BY) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (CREATED_BY) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (UPDATED_BY) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (DELETED_BY) REFERENCES AUTH_USERS(USER_ID)
);

-- 컬럼 코멘트 추가
COMMENT ON COLUMN POS_STORE_USER_ROLES.STORE_USER_ROLE_ID IS '매장별 사용자 역할 ID (Primary Key)';
COMMENT ON COLUMN POS_STORE_USER_ROLES.STORE_ID IS '매장 ID (Foreign Key: POS_STORES.STORE_ID)';
COMMENT ON COLUMN POS_STORE_USER_ROLES.USER_ID IS '사용자 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN POS_STORE_USER_ROLES.ROLE_ID IS '역할 ID (Foreign Key: AUTH_ROLES.ROLE_ID)';
COMMENT ON COLUMN POS_STORE_USER_ROLES.GRANTED_AT IS '권한 부여 시간';
COMMENT ON COLUMN POS_STORE_USER_ROLES.GRANTED_BY IS '권한 부여자 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN POS_STORE_USER_ROLES.EXPIRES_AT IS '권한 만료 시간 (NULL이면 무기한)';
COMMENT ON COLUMN POS_STORE_USER_ROLES.STATUS IS '권한 상태 (ACTIVE:활성, INACTIVE:비활성, SUSPENDED:정지)';
COMMENT ON COLUMN POS_STORE_USER_ROLES.NOTES IS '권한 부여 사유 및 메모';
COMMENT ON COLUMN POS_STORE_USER_ROLES.CREATED_AT IS '생성 시간';
COMMENT ON COLUMN POS_STORE_USER_ROLES.CREATED_BY IS '생성자 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN POS_STORE_USER_ROLES.UPDATED_AT IS '수정 시간';
COMMENT ON COLUMN POS_STORE_USER_ROLES.UPDATED_BY IS '수정자 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN POS_STORE_USER_ROLES.IS_DELETED IS '삭제 여부 (Y:삭제, N:미삭제)';
COMMENT ON COLUMN POS_STORE_USER_ROLES.DELETED_AT IS '삭제 시간';
COMMENT ON COLUMN POS_STORE_USER_ROLES.DELETED_BY IS '삭제자 ID (Foreign Key: AUTH_USERS.USER_ID)'; 