-- ============================================================================
-- Placely 프로젝트 Oracle DB 전체 테이블 생성 스크립트 (코멘트 포함 버전) - Part 2
-- ============================================================================

-- 카테고리 테이블
CREATE TABLE POS_CATEGORIES (
    CATEGORY_ID     NUMBER          PRIMARY KEY,
    CATEGORY_NAME   VARCHAR2(100)   NOT NULL,
    PARENT_ID       NUMBER,
    DISPLAY_ORDER   NUMBER          DEFAULT 0,
    STATUS          VARCHAR2(20)    DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'INACTIVE')),
    CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY      NUMBER,
    UPDATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY      NUMBER,
    IS_DELETED      CHAR(1)         DEFAULT 'N' CHECK (IS_DELETED IN ('Y', 'N')),
    DELETED_AT      TIMESTAMP,
    DELETED_BY      NUMBER,
    FOREIGN KEY (PARENT_ID) REFERENCES POS_CATEGORIES(CATEGORY_ID),
    FOREIGN KEY (CREATED_BY) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (UPDATED_BY) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (DELETED_BY) REFERENCES AUTH_USERS(USER_ID)
);

-- 컬럼 코멘트 추가
COMMENT ON COLUMN POS_CATEGORIES.CATEGORY_ID IS '카테고리 ID (Primary Key)';
COMMENT ON COLUMN POS_CATEGORIES.CATEGORY_NAME IS '카테고리명';
COMMENT ON COLUMN POS_CATEGORIES.PARENT_ID IS '상위 카테고리 ID (Foreign Key: POS_CATEGORIES.CATEGORY_ID)';
COMMENT ON COLUMN POS_CATEGORIES.DISPLAY_ORDER IS '표시 순서';
COMMENT ON COLUMN POS_CATEGORIES.STATUS IS '카테고리 상태 (ACTIVE:활성, INACTIVE:비활성)';
COMMENT ON COLUMN POS_CATEGORIES.CREATED_AT IS '생성 시간';
COMMENT ON COLUMN POS_CATEGORIES.CREATED_BY IS '생성자 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN POS_CATEGORIES.UPDATED_AT IS '수정 시간';
COMMENT ON COLUMN POS_CATEGORIES.UPDATED_BY IS '수정자 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN POS_CATEGORIES.IS_DELETED IS '삭제 여부 (Y:삭제, N:미삭제)';
COMMENT ON COLUMN POS_CATEGORIES.DELETED_AT IS '삭제 시간';
COMMENT ON COLUMN POS_CATEGORIES.DELETED_BY IS '삭제자 ID (Foreign Key: AUTH_USERS.USER_ID)';

-- 옵션 그룹 테이블
CREATE TABLE POS_OPTION_GROUPS (
    OPTION_GROUP_ID NUMBER          PRIMARY KEY,
    GROUP_NAME      VARCHAR2(50)    NOT NULL,
    DESCRIPTION     VARCHAR2(200),
    CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY      NUMBER,
    UPDATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY      NUMBER,
    IS_DELETED      CHAR(1)         DEFAULT 'N' CHECK (IS_DELETED IN ('Y', 'N')),
    DELETED_AT      TIMESTAMP,
    DELETED_BY      NUMBER,
    FOREIGN KEY (CREATED_BY) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (UPDATED_BY) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (DELETED_BY) REFERENCES AUTH_USERS(USER_ID)
);

-- 컬럼 코멘트 추가
COMMENT ON COLUMN POS_OPTION_GROUPS.OPTION_GROUP_ID IS '옵션 그룹 ID (Primary Key)';
COMMENT ON COLUMN POS_OPTION_GROUPS.GROUP_NAME IS '옵션 그룹명 (예: 사이즈, 온도, 시럽)';
COMMENT ON COLUMN POS_OPTION_GROUPS.DESCRIPTION IS '옵션 그룹 설명';
COMMENT ON COLUMN POS_OPTION_GROUPS.CREATED_AT IS '생성 시간';
COMMENT ON COLUMN POS_OPTION_GROUPS.CREATED_BY IS '생성자 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN POS_OPTION_GROUPS.UPDATED_AT IS '수정 시간';
COMMENT ON COLUMN POS_OPTION_GROUPS.UPDATED_BY IS '수정자 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN POS_OPTION_GROUPS.IS_DELETED IS '삭제 여부 (Y:삭제, N:미삭제)';
COMMENT ON COLUMN POS_OPTION_GROUPS.DELETED_AT IS '삭제 시간';
COMMENT ON COLUMN POS_OPTION_GROUPS.DELETED_BY IS '삭제자 ID (Foreign Key: AUTH_USERS.USER_ID)';

-- 옵션 항목 테이블
CREATE TABLE POS_OPTION_ITEMS (
    OPTION_ITEM_ID  NUMBER          PRIMARY KEY,
    OPTION_GROUP_ID NUMBER          NOT NULL,
    ITEM_NAME       VARCHAR2(50)    NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY      NUMBER,
    UPDATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY      NUMBER,
    IS_DELETED      CHAR(1)         DEFAULT 'N' CHECK (IS_DELETED IN ('Y', 'N')),
    DELETED_AT      TIMESTAMP,
    DELETED_BY      NUMBER,
    FOREIGN KEY (OPTION_GROUP_ID) REFERENCES POS_OPTION_GROUPS(OPTION_GROUP_ID),
    FOREIGN KEY (CREATED_BY) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (UPDATED_BY) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (DELETED_BY) REFERENCES AUTH_USERS(USER_ID)
);

-- 컬럼 코멘트 추가
COMMENT ON COLUMN POS_OPTION_ITEMS.OPTION_ITEM_ID IS '옵션 항목 ID (Primary Key)';
COMMENT ON COLUMN POS_OPTION_ITEMS.OPTION_GROUP_ID IS '옵션 그룹 ID (Foreign Key: POS_OPTION_GROUPS.OPTION_GROUP_ID)';
COMMENT ON COLUMN POS_OPTION_ITEMS.ITEM_NAME IS '옵션 항목명 (예: S, M, L, 아이스, 핫, 바닐라시럽)';
COMMENT ON COLUMN POS_OPTION_ITEMS.CREATED_AT IS '생성 시간';
COMMENT ON COLUMN POS_OPTION_ITEMS.CREATED_BY IS '생성자 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN POS_OPTION_ITEMS.UPDATED_AT IS '수정 시간';
COMMENT ON COLUMN POS_OPTION_ITEMS.UPDATED_BY IS '수정자 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN POS_OPTION_ITEMS.IS_DELETED IS '삭제 여부 (Y:삭제, N:미삭제)';
COMMENT ON COLUMN POS_OPTION_ITEMS.DELETED_AT IS '삭제 시간';
COMMENT ON COLUMN POS_OPTION_ITEMS.DELETED_BY IS '삭제자 ID (Foreign Key: AUTH_USERS.USER_ID)';

-- 상품 테이블
CREATE TABLE POS_PRODUCTS (
    PRODUCT_ID      NUMBER          PRIMARY KEY,
    STORE_ID        NUMBER          NOT NULL,
    PRODUCT_NAME    VARCHAR2(200)   NOT NULL,
    PRODUCT_CODE    VARCHAR2(50)    NOT NULL,
    BARCODE         VARCHAR2(50),
    CATEGORY_ID     NUMBER,
    BASE_PRICE      NUMBER(10,2)    NOT NULL CHECK (BASE_PRICE >= 0),
    COST_PRICE      NUMBER(10,2)    CHECK (COST_PRICE >= 0),
    TAX_RATE        NUMBER(5,2)     DEFAULT 10.0,
    DESCRIPTION     VARCHAR2(500),
    IMAGE_URL       VARCHAR2(300),
    IS_ACTIVE       CHAR(1)         DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N')),
    CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY      NUMBER,
    UPDATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY      NUMBER,
    IS_DELETED      CHAR(1)         DEFAULT 'N' CHECK (IS_DELETED IN ('Y', 'N')),
    DELETED_AT      TIMESTAMP,
    DELETED_BY      NUMBER,
    UNIQUE (STORE_ID, PRODUCT_CODE),
    FOREIGN KEY (STORE_ID) REFERENCES POS_STORES(STORE_ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES POS_CATEGORIES(CATEGORY_ID),
    FOREIGN KEY (CREATED_BY) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (UPDATED_BY) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (DELETED_BY) REFERENCES AUTH_USERS(USER_ID)
);

-- 컬럼 코멘트 추가
COMMENT ON COLUMN POS_PRODUCTS.PRODUCT_ID IS '상품 ID (Primary Key)';
COMMENT ON COLUMN POS_PRODUCTS.STORE_ID IS '매장 ID (Foreign Key: POS_STORES.STORE_ID)';
COMMENT ON COLUMN POS_PRODUCTS.PRODUCT_NAME IS '상품명';
COMMENT ON COLUMN POS_PRODUCTS.PRODUCT_CODE IS '상품 코드';
COMMENT ON COLUMN POS_PRODUCTS.BARCODE IS '바코드';
COMMENT ON COLUMN POS_PRODUCTS.CATEGORY_ID IS '카테고리 ID (Foreign Key: POS_CATEGORIES.CATEGORY_ID)';
COMMENT ON COLUMN POS_PRODUCTS.BASE_PRICE IS '기본 가격';
COMMENT ON COLUMN POS_PRODUCTS.COST_PRICE IS '원가';
COMMENT ON COLUMN POS_PRODUCTS.TAX_RATE IS '세율 (%)';
COMMENT ON COLUMN POS_PRODUCTS.DESCRIPTION IS '상품 설명';
COMMENT ON COLUMN POS_PRODUCTS.IMAGE_URL IS '상품 이미지 URL';
COMMENT ON COLUMN POS_PRODUCTS.IS_ACTIVE IS '판매 여부 (Y:판매, N:미판매)';
COMMENT ON COLUMN POS_PRODUCTS.CREATED_AT IS '생성 시간';
COMMENT ON COLUMN POS_PRODUCTS.CREATED_BY IS '생성자 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN POS_PRODUCTS.UPDATED_AT IS '수정 시간';
COMMENT ON COLUMN POS_PRODUCTS.UPDATED_BY IS '수정자 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN POS_PRODUCTS.IS_DELETED IS '삭제 여부 (Y:삭제, N:미삭제)';
COMMENT ON COLUMN POS_PRODUCTS.DELETED_AT IS '삭제 시간';
COMMENT ON COLUMN POS_PRODUCTS.DELETED_BY IS '삭제자 ID (Foreign Key: AUTH_USERS.USER_ID)';

-- 상품-옵션 연결 테이블
CREATE TABLE POS_PRODUCT_OPTIONS (
    PRODUCT_OPTION_ID NUMBER        PRIMARY KEY,
    PRODUCT_ID        NUMBER        NOT NULL,
    OPTION_ITEM_ID    NUMBER        NOT NULL,
    EXTRA_PRICE       NUMBER(10,2)  DEFAULT 0,
    CREATED_AT        TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (PRODUCT_ID, OPTION_ITEM_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES POS_PRODUCTS(PRODUCT_ID),
    FOREIGN KEY (OPTION_ITEM_ID) REFERENCES POS_OPTION_ITEMS(OPTION_ITEM_ID)
);

-- 컬럼 코멘트 추가
COMMENT ON COLUMN POS_PRODUCT_OPTIONS.PRODUCT_OPTION_ID IS '상품-옵션 연결 ID (Primary Key)';
COMMENT ON COLUMN POS_PRODUCT_OPTIONS.PRODUCT_ID IS '상품 ID (Foreign Key: POS_PRODUCTS.PRODUCT_ID)';
COMMENT ON COLUMN POS_PRODUCT_OPTIONS.OPTION_ITEM_ID IS '옵션 항목 ID (Foreign Key: POS_OPTION_ITEMS.OPTION_ITEM_ID)';
COMMENT ON COLUMN POS_PRODUCT_OPTIONS.EXTRA_PRICE IS '추가 금액';
COMMENT ON COLUMN POS_PRODUCT_OPTIONS.CREATED_AT IS '생성 시간';

-- 재고 테이블
CREATE TABLE POS_INVENTORY (
    INVENTORY_ID    NUMBER          PRIMARY KEY,
    STORE_ID        NUMBER          NOT NULL,
    PRODUCT_ID      NUMBER          NOT NULL,
    CURRENT_STOCK   NUMBER          DEFAULT 0 CHECK (CURRENT_STOCK >= 0),
    MIN_STOCK       NUMBER          DEFAULT 0,
    MAX_STOCK       NUMBER,
    LAST_UPDATED    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY      NUMBER,
    UPDATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY      NUMBER,
    IS_DELETED      CHAR(1)         DEFAULT 'N' CHECK (IS_DELETED IN ('Y', 'N')),
    DELETED_AT      TIMESTAMP,
    DELETED_BY      NUMBER,
    UNIQUE (STORE_ID, PRODUCT_ID),
    FOREIGN KEY (STORE_ID) REFERENCES POS_STORES(STORE_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES POS_PRODUCTS(PRODUCT_ID),
    FOREIGN KEY (CREATED_BY) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (UPDATED_BY) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (DELETED_BY) REFERENCES AUTH_USERS(USER_ID)
);

-- 컬럼 코멘트 추가
COMMENT ON COLUMN POS_INVENTORY.INVENTORY_ID IS '재고 ID (Primary Key)';
COMMENT ON COLUMN POS_INVENTORY.STORE_ID IS '매장 ID (Foreign Key: POS_STORES.STORE_ID)';
COMMENT ON COLUMN POS_INVENTORY.PRODUCT_ID IS '상품 ID (Foreign Key: POS_PRODUCTS.PRODUCT_ID)';
COMMENT ON COLUMN POS_INVENTORY.CURRENT_STOCK IS '현재 재고량';
COMMENT ON COLUMN POS_INVENTORY.MIN_STOCK IS '최소 재고량';
COMMENT ON COLUMN POS_INVENTORY.MAX_STOCK IS '최대 재고량';
COMMENT ON COLUMN POS_INVENTORY.LAST_UPDATED IS '최종 업데이트 시간';
COMMENT ON COLUMN POS_INVENTORY.CREATED_AT IS '생성 시간';
COMMENT ON COLUMN POS_INVENTORY.CREATED_BY IS '생성자 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN POS_INVENTORY.UPDATED_AT IS '수정 시간';
COMMENT ON COLUMN POS_INVENTORY.UPDATED_BY IS '수정자 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN POS_INVENTORY.IS_DELETED IS '삭제 여부 (Y:삭제, N:미삭제)';
COMMENT ON COLUMN POS_INVENTORY.DELETED_AT IS '삭제 시간';
COMMENT ON COLUMN POS_INVENTORY.DELETED_BY IS '삭제자 ID (Foreign Key: AUTH_USERS.USER_ID)';

-- 판매 테이블
CREATE TABLE POS_SALES (
    SALE_ID         NUMBER          PRIMARY KEY,
    STORE_ID        NUMBER          NOT NULL,
    CASHIER_ID      NUMBER          NOT NULL,
    RECEIPT_NUMBER  VARCHAR2(50)    UNIQUE NOT NULL,
    TOTAL_AMOUNT    NUMBER(12,2)    NOT NULL CHECK (TOTAL_AMOUNT >= 0),
    TAX_AMOUNT      NUMBER(12,2)    DEFAULT 0,
    DISCOUNT_AMOUNT NUMBER(10,2)    DEFAULT 0,
    PAYMENT_METHOD  VARCHAR2(20)    CHECK (PAYMENT_METHOD IN ('CASH', 'CARD', 'QR', 'MIXED')),
    SALE_DATE       TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    STATUS          VARCHAR2(20)    DEFAULT 'COMPLETED' CHECK (STATUS IN ('COMPLETED', 'CANCELLED', 'REFUNDED')),
    CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY      NUMBER,
    UPDATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY      NUMBER,
    IS_DELETED      CHAR(1)         DEFAULT 'N' CHECK (IS_DELETED IN ('Y', 'N')),
    DELETED_AT      TIMESTAMP,
    DELETED_BY      NUMBER,
    FOREIGN KEY (STORE_ID) REFERENCES POS_STORES(STORE_ID),
    FOREIGN KEY (CASHIER_ID) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (CREATED_BY) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (UPDATED_BY) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (DELETED_BY) REFERENCES AUTH_USERS(USER_ID)
);

-- 컬럼 코멘트 추가
COMMENT ON COLUMN POS_SALES.SALE_ID IS '판매 ID (Primary Key)';
COMMENT ON COLUMN POS_SALES.STORE_ID IS '매장 ID (Foreign Key: POS_STORES.STORE_ID)';
COMMENT ON COLUMN POS_SALES.CASHIER_ID IS '계산원 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN POS_SALES.RECEIPT_NUMBER IS '영수증 번호';
COMMENT ON COLUMN POS_SALES.TOTAL_AMOUNT IS '총 판매금액';
COMMENT ON COLUMN POS_SALES.TAX_AMOUNT IS '세금';
COMMENT ON COLUMN POS_SALES.DISCOUNT_AMOUNT IS '할인금액';
COMMENT ON COLUMN POS_SALES.PAYMENT_METHOD IS '결제 방법 (CASH:현금, CARD:카드, QR:QR결제, MIXED:혼합결제)';
COMMENT ON COLUMN POS_SALES.SALE_DATE IS '판매 일시';
COMMENT ON COLUMN POS_SALES.STATUS IS '판매 상태 (COMPLETED:완료, CANCELLED:취소, REFUNDED:환불)';
COMMENT ON COLUMN POS_SALES.CREATED_AT IS '생성 시간';
COMMENT ON COLUMN POS_SALES.CREATED_BY IS '생성자 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN POS_SALES.UPDATED_AT IS '수정 시간';
COMMENT ON COLUMN POS_SALES.UPDATED_BY IS '수정자 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN POS_SALES.IS_DELETED IS '삭제 여부 (Y:삭제, N:미삭제)';
COMMENT ON COLUMN POS_SALES.DELETED_AT IS '삭제 시간';
COMMENT ON COLUMN POS_SALES.DELETED_BY IS '삭제자 ID (Foreign Key: AUTH_USERS.USER_ID)';

-- 판매 상세 테이블
CREATE TABLE POS_SALE_ITEMS (
    SALE_ITEM_ID    NUMBER          PRIMARY KEY,
    SALE_ID         NUMBER          NOT NULL,
    PRODUCT_ID      NUMBER          NOT NULL,
    QUANTITY        NUMBER          NOT NULL CHECK (QUANTITY > 0),
    BASE_PRICE      NUMBER(10,2)    NOT NULL CHECK (BASE_PRICE >= 0),
    TOTAL_AMOUNT    NUMBER(12,2)    NOT NULL CHECK (TOTAL_AMOUNT >= 0),
    DISCOUNT_AMOUNT NUMBER(10,2)    DEFAULT 0,
    TAX_AMOUNT      NUMBER(10,2)    DEFAULT 0,
    CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY      NUMBER,
    UPDATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY      NUMBER,
    IS_DELETED      CHAR(1)         DEFAULT 'N' CHECK (IS_DELETED IN ('Y', 'N')),
    DELETED_AT      TIMESTAMP,
    DELETED_BY      NUMBER,
    FOREIGN KEY (SALE_ID) REFERENCES POS_SALES(SALE_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES POS_PRODUCTS(PRODUCT_ID),
    FOREIGN KEY (CREATED_BY) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (UPDATED_BY) REFERENCES AUTH_USERS(USER_ID),
    FOREIGN KEY (DELETED_BY) REFERENCES AUTH_USERS(USER_ID)
);

-- 컬럼 코멘트 추가
COMMENT ON COLUMN POS_SALE_ITEMS.SALE_ITEM_ID IS '판매 상세 ID (Primary Key)';
COMMENT ON COLUMN POS_SALE_ITEMS.SALE_ID IS '판매 ID (Foreign Key: POS_SALES.SALE_ID)';
COMMENT ON COLUMN POS_SALE_ITEMS.PRODUCT_ID IS '상품 ID (Foreign Key: POS_PRODUCTS.PRODUCT_ID)';
COMMENT ON COLUMN POS_SALE_ITEMS.QUANTITY IS '수량';
COMMENT ON COLUMN POS_SALE_ITEMS.BASE_PRICE IS '기본 가격';
COMMENT ON COLUMN POS_SALE_ITEMS.TOTAL_AMOUNT IS '총 금액';
COMMENT ON COLUMN POS_SALE_ITEMS.DISCOUNT_AMOUNT IS '할인 금액';
COMMENT ON COLUMN POS_SALE_ITEMS.TAX_AMOUNT IS '세금';
COMMENT ON COLUMN POS_SALE_ITEMS.CREATED_AT IS '생성 시간';
COMMENT ON COLUMN POS_SALE_ITEMS.CREATED_BY IS '생성자 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN POS_SALE_ITEMS.UPDATED_AT IS '수정 시간';
COMMENT ON COLUMN POS_SALE_ITEMS.UPDATED_BY IS '수정자 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN POS_SALE_ITEMS.IS_DELETED IS '삭제 여부 (Y:삭제, N:미삭제)';
COMMENT ON COLUMN POS_SALE_ITEMS.DELETED_AT IS '삭제 시간';
COMMENT ON COLUMN POS_SALE_ITEMS.DELETED_BY IS '삭제자 ID (Foreign Key: AUTH_USERS.USER_ID)';

-- 판매 상세 옵션 테이블
CREATE TABLE POS_SALE_ITEM_OPTIONS (
    SALE_OPTION_ID    NUMBER        PRIMARY KEY,
    SALE_ITEM_ID      NUMBER        NOT NULL,
    PRODUCT_OPTION_ID NUMBER        NOT NULL,
    OPTION_NAME       VARCHAR2(50)  NOT NULL,
    OPTION_PRICE      NUMBER(10,2)  DEFAULT 0,
    CREATED_AT        TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SALE_ITEM_ID) REFERENCES POS_SALE_ITEMS(SALE_ITEM_ID),
    FOREIGN KEY (PRODUCT_OPTION_ID) REFERENCES POS_PRODUCT_OPTIONS(PRODUCT_OPTION_ID)
);

-- 컬럼 코멘트 추가
COMMENT ON COLUMN POS_SALE_ITEM_OPTIONS.SALE_OPTION_ID IS '판매 옵션 ID (Primary Key)';
COMMENT ON COLUMN POS_SALE_ITEM_OPTIONS.SALE_ITEM_ID IS '판매 상세 ID (Foreign Key: POS_SALE_ITEMS.SALE_ITEM_ID)';
COMMENT ON COLUMN POS_SALE_ITEM_OPTIONS.PRODUCT_OPTION_ID IS '상품 옵션 ID (Foreign Key: POS_PRODUCT_OPTIONS.PRODUCT_OPTION_ID)';
COMMENT ON COLUMN POS_SALE_ITEM_OPTIONS.OPTION_NAME IS '옵션명 (주문 시점 기록)';
COMMENT ON COLUMN POS_SALE_ITEM_OPTIONS.OPTION_PRICE IS '옵션 추가 금액';
COMMENT ON COLUMN POS_SALE_ITEM_OPTIONS.CREATED_AT IS '생성 시간';

-- 결제 테이블
CREATE TABLE POS_PAYMENTS (
    PAYMENT_ID      NUMBER          PRIMARY KEY,
    SALE_ID         NUMBER          NOT NULL,
    PAYMENT_METHOD  VARCHAR2(20)    NOT NULL CHECK (PAYMENT_METHOD IN ('CASH', 'CARD', 'QR')),
    AMOUNT          NUMBER(12,2)    NOT NULL CHECK (AMOUNT > 0),
    CARD_NUMBER     VARCHAR2(20),
    APPROVAL_NUMBER VARCHAR2(50),
    PAYMENT_DATE    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    STATUS          VARCHAR2(20)    DEFAULT 'COMPLETED' CHECK (STATUS IN ('COMPLETED', 'CANCELLED')),
    CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SALE_ID) REFERENCES POS_SALES(SALE_ID)
);

-- 컬럼 코멘트 추가
COMMENT ON COLUMN POS_PAYMENTS.PAYMENT_ID IS '결제 ID (Primary Key)';
COMMENT ON COLUMN POS_PAYMENTS.SALE_ID IS '판매 ID (Foreign Key: POS_SALES.SALE_ID)';
COMMENT ON COLUMN POS_PAYMENTS.PAYMENT_METHOD IS '결제 방법 (CASH:현금, CARD:카드, QR:QR결제)';
COMMENT ON COLUMN POS_PAYMENTS.AMOUNT IS '결제 금액';
COMMENT ON COLUMN POS_PAYMENTS.CARD_NUMBER IS '마스킹된 카드 번호';
COMMENT ON COLUMN POS_PAYMENTS.APPROVAL_NUMBER IS '승인 번호';
COMMENT ON COLUMN POS_PAYMENTS.PAYMENT_DATE IS '결제 일시';
COMMENT ON COLUMN POS_PAYMENTS.STATUS IS '결제 상태 (COMPLETED:완료, CANCELLED:취소)';
COMMENT ON COLUMN POS_PAYMENTS.CREATED_AT IS '생성 시간';

-- 재고 이동 이력 테이블
CREATE TABLE POS_INVENTORY_MOVEMENTS (
    MOVEMENT_ID     NUMBER          PRIMARY KEY,
    STORE_ID        NUMBER          NOT NULL,
    PRODUCT_ID      NUMBER          NOT NULL,
    MOVEMENT_TYPE   VARCHAR2(20)    NOT NULL CHECK (MOVEMENT_TYPE IN ('IN', 'OUT', 'ADJUST')),
    QUANTITY        NUMBER          NOT NULL,
    REFERENCE_TYPE  VARCHAR2(20),
    REFERENCE_ID    NUMBER,
    MOVEMENT_DATE   TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    NOTES           VARCHAR2(200),
    CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (STORE_ID) REFERENCES POS_STORES(STORE_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES POS_PRODUCTS(PRODUCT_ID)
);

-- 컬럼 코멘트 추가
COMMENT ON COLUMN POS_INVENTORY_MOVEMENTS.MOVEMENT_ID IS '재고 이동 ID (Primary Key)';
COMMENT ON COLUMN POS_INVENTORY_MOVEMENTS.STORE_ID IS '매장 ID (Foreign Key: POS_STORES.STORE_ID)';
COMMENT ON COLUMN POS_INVENTORY_MOVEMENTS.PRODUCT_ID IS '상품 ID (Foreign Key: POS_PRODUCTS.PRODUCT_ID)';
COMMENT ON COLUMN POS_INVENTORY_MOVEMENTS.MOVEMENT_TYPE IS '이동 타입 (IN:입고, OUT:출고, ADJUST:조정)';
COMMENT ON COLUMN POS_INVENTORY_MOVEMENTS.QUANTITY IS '이동 수량';
COMMENT ON COLUMN POS_INVENTORY_MOVEMENTS.REFERENCE_TYPE IS '참조 타입 (SALE:판매, PURCHASE:입고, ADJUST:조정)';
COMMENT ON COLUMN POS_INVENTORY_MOVEMENTS.REFERENCE_ID IS '참조 ID';
COMMENT ON COLUMN POS_INVENTORY_MOVEMENTS.MOVEMENT_DATE IS '이동 일시';
COMMENT ON COLUMN POS_INVENTORY_MOVEMENTS.NOTES IS '메모';
COMMENT ON COLUMN POS_INVENTORY_MOVEMENTS.CREATED_AT IS '생성 시간';

-- ============================================================================
-- AI 서비스 테이블 (AI 기반 추천 및 분석)
-- ============================================================================

-- 고객 행동 분석 테이블
CREATE TABLE AI_CUSTOMER_BEHAVIOR (
    BEHAVIOR_ID     NUMBER          PRIMARY KEY,
    STORE_ID        NUMBER          NOT NULL,
    SESSION_ID      VARCHAR2(100),
    CUSTOMER_TYPE   VARCHAR2(20)    CHECK (CUSTOMER_TYPE IN ('MEMBER', 'GUEST')),
    AGE_GROUP       VARCHAR2(20),
    GENDER          CHAR(1)         CHECK (GENDER IN ('M', 'F', 'U')),
    VISIT_TIME      TIMESTAMP       NOT NULL,
    VISIT_DURATION  NUMBER,
    TOTAL_AMOUNT    NUMBER(12,2),
    ITEMS_COUNT     NUMBER,
    BEHAVIOR_TYPE   VARCHAR2(50),
    CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (STORE_ID) REFERENCES POS_STORES(STORE_ID)
);

-- 컬럼 코멘트 추가
COMMENT ON COLUMN AI_CUSTOMER_BEHAVIOR.BEHAVIOR_ID IS '고객 행동 ID (Primary Key)';
COMMENT ON COLUMN AI_CUSTOMER_BEHAVIOR.STORE_ID IS '매장 ID (Foreign Key: POS_STORES.STORE_ID)';
COMMENT ON COLUMN AI_CUSTOMER_BEHAVIOR.SESSION_ID IS '세션 ID';
COMMENT ON COLUMN AI_CUSTOMER_BEHAVIOR.CUSTOMER_TYPE IS '고객 타입 (MEMBER:회원, GUEST:비회원)';
COMMENT ON COLUMN AI_CUSTOMER_BEHAVIOR.AGE_GROUP IS '연령대 (10s, 20s, 30s, 40s, 50s, 60+)';
COMMENT ON COLUMN AI_CUSTOMER_BEHAVIOR.GENDER IS '성별 (M:남성, F:여성, U:미상)';
COMMENT ON COLUMN AI_CUSTOMER_BEHAVIOR.VISIT_TIME IS '방문 시간';
COMMENT ON COLUMN AI_CUSTOMER_BEHAVIOR.VISIT_DURATION IS '방문 시간 (분)';
COMMENT ON COLUMN AI_CUSTOMER_BEHAVIOR.TOTAL_AMOUNT IS '총 구매 금액';
COMMENT ON COLUMN AI_CUSTOMER_BEHAVIOR.ITEMS_COUNT IS '구매 상품 수';
COMMENT ON COLUMN AI_CUSTOMER_BEHAVIOR.BEHAVIOR_TYPE IS '행동 타입 (BROWSE:둘러보기, PURCHASE:구매, RETURN:반품)';
COMMENT ON COLUMN AI_CUSTOMER_BEHAVIOR.CREATED_AT IS '생성 시간';

-- 상품 추천 이력 테이블
CREATE TABLE AI_RECOMMENDATIONS (
    RECOMMENDATION_ID   NUMBER      PRIMARY KEY,
    STORE_ID           NUMBER       NOT NULL,
    PRODUCT_ID         NUMBER       NOT NULL,
    CUSTOMER_ID        NUMBER,
    RECOMMENDATION_TYPE VARCHAR2(30) CHECK (RECOMMENDATION_TYPE IN ('POPULAR', 'SIMILAR', 'CROSS_SELL', 'SEASONAL')),
    SCORE_VALUE        NUMBER(5,2),
    ALGORITHM_VERSION  VARCHAR2(20),
    RECOMMENDED_AT     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CLICKED           CHAR(1)       DEFAULT 'N' CHECK (CLICKED IN ('Y', 'N')),
    PURCHASED         CHAR(1)       DEFAULT 'N' CHECK (PURCHASED IN ('Y', 'N')),
    CLICKED_AT        TIMESTAMP,
    PURCHASED_AT      TIMESTAMP,
    FOREIGN KEY (STORE_ID) REFERENCES POS_STORES(STORE_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES POS_PRODUCTS(PRODUCT_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES AUTH_USERS(USER_ID)
);

-- 컬럼 코멘트 추가
COMMENT ON COLUMN AI_RECOMMENDATIONS.RECOMMENDATION_ID IS '추천 ID (Primary Key)';
COMMENT ON COLUMN AI_RECOMMENDATIONS.STORE_ID IS '매장 ID (Foreign Key: POS_STORES.STORE_ID)';
COMMENT ON COLUMN AI_RECOMMENDATIONS.PRODUCT_ID IS '상품 ID (Foreign Key: POS_PRODUCTS.PRODUCT_ID)';
COMMENT ON COLUMN AI_RECOMMENDATIONS.CUSTOMER_ID IS '고객 ID (Foreign Key: AUTH_USERS.USER_ID)';
COMMENT ON COLUMN AI_RECOMMENDATIONS.RECOMMENDATION_TYPE IS '추천 타입 (POPULAR:인기상품, SIMILAR:유사상품, CROSS_SELL:교차판매, SEASONAL:계절상품)';
COMMENT ON COLUMN AI_RECOMMENDATIONS.SCORE_VALUE IS '추천 점수 (0-100)';
COMMENT ON COLUMN AI_RECOMMENDATIONS.ALGORITHM_VERSION IS '알고리즘 버전';
COMMENT ON COLUMN AI_RECOMMENDATIONS.RECOMMENDED_AT IS '추천 시간';
COMMENT ON COLUMN AI_RECOMMENDATIONS.CLICKED IS '클릭 여부 (Y:클릭, N:미클릭)';
COMMENT ON COLUMN AI_RECOMMENDATIONS.PURCHASED IS '구매 여부 (Y:구매, N:미구매)';
COMMENT ON COLUMN AI_RECOMMENDATIONS.CLICKED_AT IS '클릭 시간';
COMMENT ON COLUMN AI_RECOMMENDATIONS.PURCHASED_AT IS '구매 시간'; 