server:
  port: 8081
  servlet:
    context-path: /auth

spring:
  application:
    name: auth-service

  # common 모듈 설정 포함
  profiles:
    include:
      - common
      - env # gitignore 처리

  # 데이터베이스 설정
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${datasource.url}
    username: ${datasource.usr}
    password: ${datasource.pwd}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: none # 운영에서는 none, 개발시에는 validate
    show-sql: false # hibernate 로그
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true # SQL 보기 좋게
        use_sql_comments: true # JPQL 주석 보기
    open-in-view: false # 기본 true, 영속성 Service 또는 @Transactional 내부에서만 유효. View or Controller 에서 Lazy 로딩 시 예외 발생

  # Redis 설정 (토큰 관리용) - 올바른 경로로 수정
  data:
    redis:
      username: ${oracle.cloud.redis.username}
      password: ${oracle.cloud.redis.pwd}
      sentinel:
        master: mymaster
        nodes:
          - ${oracle.cloud.server1} # 이미 포트 포함됨
          - ${oracle.cloud.server2} # 이미 포트 포함됨

# 로깅 설정
logging:
  level:
    com.placely.auth: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE #  Hibernate 6.x 이상
  #    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  #  file:
  #    name: ../logs/auth-service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Actuator 설정 (헬스체크용)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# SpringDoc OpenAPI 설정
springdoc:
  api-docs:
    path: /api-docs # OpenAPI JSON 경로
    enabled: true
  swagger-ui:
    path: /swagger-ui.html # Swagger UI 경로
    enabled: true
    operations-sorter: method # API 정렬 방식 (method/alpha)
    tags-sorter: alpha # 태그 정렬 방식
    try-it-out-enabled: true # Try it out 버튼 활성화
  packages-to-scan: com.placely.auth.controller # 스캔할 패키지 지정

# 개발 환경 설정
---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: INFO
    com.placely.auth: DEBUG

# 개발환경에서 OpenAPI 문서 상세 정보 활성화
springdoc:
  swagger-ui:
    display-request-duration: true # 요청 시간 표시
    show-extensions: true # 확장 정보 표시
    show-common-extensions: true # 공통 확장 정보 표시

# 운영 환경 설정
---
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: false

logging:
  level:
    root: WARN
    com.placely.auth: INFO

# 운영환경에서 Swagger UI 비활성화 (보안)
springdoc:
  swagger-ui:
    enabled: false # 운영환경에서는 Swagger UI 비활성화
  api-docs:
    enabled: false # 운영환경에서는 API Docs도 비활성화
