server:
  port: 8081
  servlet:
    context-path: /auth

spring:
  application:
    name: auth-service

  # common 모듈 설정 포함
  profiles:
    include:
      - common
      - env # gitignore 처리

  # 데이터베이스 설정
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: placely
    password: placely123
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: none # 운영에서는 none, 개발시에는 validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false

  # Redis 설정 (토큰 관리용)
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# JWT 설정
jwt:
  secret: "placely-auth-service-jwt-secret-key-for-production-use-longer-key"
  access-token-expiration: 1800000 # 30분 (밀리초)
  refresh-token-expiration: 604800000 # 7일 (밀리초)
  issuer: "placely-auth-service"

# 로깅 설정
logging:
  level:
    com.placely.auth: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: ../logs/auth-service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Actuator 설정 (헬스체크용)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# 개발 환경 설정
---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: INFO
    com.placely.auth: DEBUG

# 운영 환경 설정
---
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: false

logging:
  level:
    root: WARN
    com.placely.auth: INFO
