server:
  port: 8081
  servlet:
    context-path: /auth

spring:
  application:
    name: auth-service

  # common 모듈 설정 포함
  profiles:
    include:
      - common
      - env # gitignore 처리

  # 데이터베이스 설정
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${datasource.url}
    username: ${datasource.usr}
    password: ${datasource.pwd}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: none # 운영에서는 none, 개발시에는 validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false

  # Redis 설정 (토큰 관리용) - 올바른 경로로 수정
  data:
    redis:
      sentinel:
        master: mymaster
        nodes:
          - ${oracle.cloud.server1} # 이미 포트 포함됨
          - ${oracle.cloud.server2} # 이미 포트 포함됨

# 로깅 설정
logging:
  level:
    com.placely.auth: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: ../logs/auth-service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Actuator 설정 (헬스체크용)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# 개발 환경 설정 - Redis 비활성화 (안전한 개발을 위해)
---
spring:
  config:
    activate:
      on-profile: dev

  # 개발환경에서는 Redis 자동설정 비활성화
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.data.redis.RedisReactiveHealthContributorAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration

logging:
  level:
    root: INFO
    com.placely.auth: DEBUG

# 운영 환경 설정 - Redis 활성화
---
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: false

logging:
  level:
    root: WARN
    com.placely.auth: INFO
